# use minimal image (Alpine w/ Python) for base
FROM python:3.12-slim AS base

# install uv binary from official distro-less image
COPY --from=ghcr.io/astral-sh/uv:0.10.0 /uv /uvx /bin/

####################
FROM base AS builder

RUN apt update \
    && apt install -y g++ git \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

# set working directory for colandr
ENV COLANDR_APP_DIR=/app
RUN mkdir -p ${COLANDR_APP_DIR}
WORKDIR ${COLANDR_APP_DIR}

# copy from cache instead of linking since it's a mounted volume
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_DOWNLOADS=0
# install dependencies only
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

################
FROM base AS dev

ENV COLANDR_APP_DIR=/app
WORKDIR ${COLANDR_APP_DIR}

# copy built artifacts from builder
COPY --from=builder --chown=app:app ${COLANDR_APP_DIR} ${COLANDR_APP_DIR}

# copy and install project
COPY . ${COLANDR_APP_DIR}
# place executables in env at the front of the path
ENV PATH="/app/.venv/bin:$PATH"
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_DOWNLOADS=0
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --group dev

# set up development env
ENV FLASK_ENV=development
# expose app port
EXPOSE 5000

CMD ["celery", "--app=make_celery.celery_app", "worker", "--loglevel=info"]

#################
FROM base AS prod

ENV COLANDR_APP_DIR=/app
WORKDIR ${COLANDR_APP_DIR}

# copy built artifacts from builder
COPY --from=builder --chown=app:app ${COLANDR_APP_DIR} ${COLANDR_APP_DIR}

# copy and install project
COPY . ${COLANDR_APP_DIR}
# place executables in env at the front of the path
ENV PATH="/app/.venv/bin:$PATH"
ENV UV_COMPILE_BYTECODE=1 UV_LINK_MODE=copy UV_PYTHON_DOWNLOADS=0
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked --no-group dev

# set up production env
ENV FLASK_ENV=production
# expose app port
EXPOSE 5000

CMD ["celery", "--app=make_celery.celery_app", "worker", "--loglevel=info", "--soft-time-limit=1800"]
