# Use a minimal image for production (e.g., an Alpine-based image with Python)
FROM python:3.11-slim AS base

# Set the working directory
ENV COLANDR_APP_DIR=/app
RUN mkdir -p ${COLANDR_APP_DIR}
WORKDIR ${COLANDR_APP_DIR}

RUN apt update \
    && apt install -y g++ git \
    && apt clean \
    && rm -rf /var/lib/apt/lists/* /usr/share/doc /usr/share/man

COPY requirements/ ./requirements/
RUN python -m pip install --upgrade pip wheel && python -m pip install -r requirements/prod.txt
RUN python -m textacy download lang_identifier --version 3.0 \
    && python -m spacy download en_core_web_md \
    && python -m spacy download es_core_news_md \
    && python -m spacy download fr_core_news_md

COPY . .

#####
FROM base AS dev

RUN python -m pip install -r requirements/dev.txt

# TODO: should we do this instead?
# RUN python -m pip install -e .[dev]

EXPOSE 5000

# flask --app "colandr.app:create_app()" run --host 0.0.0.0 --port 5000 --debug
CMD ["flask", "--app", "colandr.app:create_app()", "run", "--host", "0.0.0.0", "--port", "5000", "--debug"]

# Good for debugging
#CMD ["tail", "-f", "/dev/null"]

#####
FROM base AS prod

# Set the environment to production
ENV FLASK_ENV=production
ENV FLASK_APP=colandr.app:create_app()

# Expose the application port
EXPOSE 5000

# Use a production server (e.g., Gunicorn)
#TODO: can we return to the below line in place of the direct binding? or will this fail to deploy on GCP?
#CMD ["gunicorn", "--config", "./gunicorn.conf.py", "colandr.app:create_app()"]
CMD ["gunicorn", "-b", "0.0.0.0:5000", "colandr.app:create_app()"]
