[project]
name = "colandr"
version = "1.1.1"
description = "Back-end code for running the colandr app."
readme = { file = "README.md", content-type = "text/markdown" }
license-files = ["LICENSE"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
requires-python = ">= 3.12"
dependencies = [
  "alembic~=1.18.0",
  "apiflask~=3.0.0",
  "arrow~=1.3.0",
  "bibtexparser~=1.4.0",
  "celery[redis]~=5.5.0",
  "click~=8.3.0",
  "flask~=3.1.0",
  "flask-caching~=2.3.0",
  "Flask-Limiter~=4.0.0",
  "flask-jwt-extended~=4.7.0",
  "flask_mail~=0.10.0",
  "flask_migrate~=4.1.0",
  "flask_sqlalchemy~=3.1.0",
  "fsspec[gcs]~=2025.0",
  "ftfy~=6.3.0",
  "gunicorn~=23.0",
  "jinja2~=3.1.0",
  "joblib~=1.5.0",
  "lingua-language-detector~=2.2.0",
  "markupsafe~=3.0.0",
  "marshmallow~=4.1.0",
  "numpy~=2.4.1",
  "psycopg[binary,pool]~=3.3.0",
  "pymupdf~=1.26.0",
  "python-dateutil~=2.9.0",
  "python-dotenv~=1.2.0",
  "rispy~=0.10.0",
  "river~=0.23.0",
  "scikit-learn~=1.8.0",
  "sqlalchemy~=2.0.0",
  "spacy~=3.8.0",
  "splink~=4.0.12",
  "webargs~=8.7.0",
  "werkzeug",
  "en_core_web_md@https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl",
  "es_core_news_md@https://github.com/explosion/spacy-models/releases/download/es_core_news_md-3.8.0/es_core_news_md-3.8.0-py3-none-any.whl",
  "fr_core_news_md@https://github.com/explosion/spacy-models/releases/download/fr_core_news_md-3.8.0/fr_core_news_md-3.8.0-py3-none-any.whl",
  "ja_core_news_md@https://github.com/explosion/spacy-models/releases/download/ja_core_news_md-3.8.0/ja_core_news_md-3.8.0-py3-none-any.whl",
  "zh_core_web_md@https://github.com/explosion/spacy-models/releases/download/zh_core_web_md-3.8.0/zh_core_web_md-3.8.0-py3-none-any.whl",
]

[project.urls]
Homepage = "https://www.colandrapp.com"
Repository = "https://github.com/datakind/permanent-colandr-back"

[dependency-groups]
dev = [
  "httpx~=0.28.0",
  "pytest~=9.0",
  "pytest-postgresql~=7.0",
  "SQLAlchemy-Utils~=0.42.0",
  # TODO: update ty once officially out of beta
  "ty~=0.0.29",
  "ruff~=0.15.0",
]

[build-system]
requires = ["uv_build>=0.8.0,<0.12.0"]
build-backend = "uv_build"

[tool.uv]
required-version = ">=0.8.0,<0.12.0"

[tool.uv.build-backend]
module-name = "colandr"
module-root = ""

[tool.pytest]
minversion = "9.0"
addopts = ["--verbose"]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
indent-width = 4
target-version = "py312"
src = ["colandr"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
select = [
  "E4",     # pycodestyle
  "E7",
  "E9",
  "F",      # pyflakes
  "I",      # isort
  "PLE",    # pylint
  "PLW",
  "NPY201", # numpy v2.0
]
# ignore line-length violations, None comparisons, unused imports, overwritten assignment
ignore = ["E501", "E711", "F401", "PLW2901"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["colandr"]
known-third-party = ["alembic"]

[tool.ty.environment]
root = ["./colandr"]

[tool.ty.rules]
# ty appears to be struggling with relative imports :shrug:
unresolved-import = "ignore"

[tool.ty.src]
exclude = ["migrations", "notebooks", "tests"]

[tool.ty.terminal]
output-format = "full"
