name: "Set Up Python Environment"
description: "Set up a Python environment using uv"

inputs:
  python-version:
    description: "Python version to use"
    required: true

runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v7.6.0
      with:
        python-version: ${{ inputs.python-version }}
        version-file: "pyproject.toml"
        enable-cache: "auto"
        prune-cache: false
        ignore-nothing-to-cache: true
    - name: Install project and dependencies
      run: uv sync --frozen --dev
      shell: bash
