"""empty message

Revision ID: 03bc1be874a0
Revises: 31393355beb7
Create Date: 2016-09-16 14:06:32.154783

"""

# revision identifiers, used by Alembic.
revision = '03bc1be874a0'
down_revision = '31393355beb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fulltexts_citation_id', table_name='fulltexts')
    op.create_index(op.f('ix_fulltexts_citation_id'), 'fulltexts', ['citation_id'], unique=True)
    op.create_unique_constraint(None, 'fulltexts', ['filename'])
    op.drop_index('ix_review_plans_review_id', table_name='review_plans')
    op.create_index(op.f('ix_review_plans_review_id'), 'review_plans', ['review_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_plans_review_id'), table_name='review_plans')
    op.create_index('ix_review_plans_review_id', 'review_plans', ['review_id'], unique=False)
    op.drop_constraint(None, 'fulltexts', type_='unique')
    op.drop_index(op.f('ix_fulltexts_citation_id'), table_name='fulltexts')
    op.create_index('ix_fulltexts_citation_id', 'fulltexts', ['citation_id'], unique=False)
    ### end Alembic commands ###
