"""empty message

Revision ID: 03f0535753d7
Revises: 38a7ac82fd59
Create Date: 2016-10-27 19:04:00.821445

"""

# revision identifiers, used by Alembic.
revision = '03f0535753d7'
down_revision = '38a7ac82fd59'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citation_screenings', sa.Column('study_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('citation_review_user_study_uc', 'citation_screenings', ['review_id', 'user_id', 'study_id'])
    op.create_index(op.f('ix_citation_screenings_study_id'), 'citation_screenings', ['study_id'], unique=False)
    op.drop_index('ix_citation_screenings_citation_id', table_name='citation_screenings')
    op.drop_constraint('review_user_citation_uc', 'citation_screenings', type_='unique')
    op.drop_constraint('citation_screenings_citation_id_fkey', 'citation_screenings', type_='foreignkey')
    op.create_foreign_key(None, 'citation_screenings', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.drop_column('citation_screenings', 'citation_id')
    op.add_column('fulltext_screenings', sa.Column('study_id', sa.BigInteger(), nullable=False))
    op.create_unique_constraint('fulltext_review_user_study_uc', 'fulltext_screenings', ['review_id', 'user_id', 'study_id'])
    op.create_index(op.f('ix_fulltext_screenings_study_id'), 'fulltext_screenings', ['study_id'], unique=False)
    op.drop_index('ix_fulltext_screenings_fulltext_id', table_name='fulltext_screenings')
    op.drop_constraint('review_user_fulltext_uc', 'fulltext_screenings', type_='unique')
    op.drop_constraint('fulltext_screenings_fulltext_id_fkey', 'fulltext_screenings', type_='foreignkey')
    op.create_foreign_key(None, 'fulltext_screenings', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fulltext_screenings', 'fulltext_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulltext_screenings', sa.Column('fulltext_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fulltext_screenings', type_='foreignkey')
    op.create_foreign_key('fulltext_screenings_fulltext_id_fkey', 'fulltext_screenings', 'fulltexts', ['fulltext_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('review_user_fulltext_uc', 'fulltext_screenings', ['review_id', 'user_id', 'fulltext_id'])
    op.create_index('ix_fulltext_screenings_fulltext_id', 'fulltext_screenings', ['fulltext_id'], unique=False)
    op.drop_index(op.f('ix_fulltext_screenings_study_id'), table_name='fulltext_screenings')
    op.drop_constraint('fulltext_review_user_study_uc', 'fulltext_screenings', type_='unique')
    op.drop_column('fulltext_screenings', 'study_id')
    op.add_column('citation_screenings', sa.Column('citation_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'citation_screenings', type_='foreignkey')
    op.create_foreign_key('citation_screenings_citation_id_fkey', 'citation_screenings', 'citations', ['citation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('review_user_citation_uc', 'citation_screenings', ['review_id', 'user_id', 'citation_id'])
    op.create_index('ix_citation_screenings_citation_id', 'citation_screenings', ['citation_id'], unique=False)
    op.drop_index(op.f('ix_citation_screenings_study_id'), table_name='citation_screenings')
    op.drop_constraint('citation_review_user_study_uc', 'citation_screenings', type_='unique')
    op.drop_column('citation_screenings', 'study_id')
    ### end Alembic commands ###
