"""remove dedupe tables

Revision ID: 10e30b838ff6
Revises: acafd03652f0
Create Date: 2023-08-26 19:41:15.019613

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "10e30b838ff6"
down_revision = "acafd03652f0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dedupe_smaller_coverage", schema=None) as batch_op:
        batch_op.drop_index("ix_dedupe_smaller_coverage_citation_id")
        batch_op.drop_index("ix_dedupe_smaller_coverage_review_id")
    op.drop_table("dedupe_smaller_coverage")

    with op.batch_alter_table("dedupe_plural_key", schema=None) as batch_op:
        batch_op.drop_index("ix_dedupe_plural_key_block_key")
        batch_op.drop_index("ix_dedupe_plural_key_review_id")
    op.drop_table("dedupe_plural_key")

    with op.batch_alter_table("dedupe_blocking_map", schema=None) as batch_op:
        batch_op.drop_index("ix_dedupe_blocking_map_block_key")
        batch_op.drop_index("ix_dedupe_blocking_map_citation_id")
        batch_op.drop_index("ix_dedupe_blocking_map_review_id")
    op.drop_table("dedupe_blocking_map")

    with op.batch_alter_table("dedupe_plural_block", schema=None) as batch_op:
        batch_op.drop_index("ix_dedupe_plural_block_citation_id")
        batch_op.drop_index("ix_dedupe_plural_block_review_id")
    op.drop_table("dedupe_plural_block")

    with op.batch_alter_table("dedupe_covered_blocks", schema=None) as batch_op:
        batch_op.drop_index("ix_dedupe_covered_blocks_citation_id")
        batch_op.drop_index("ix_dedupe_covered_blocks_review_id")
    op.drop_table("dedupe_covered_blocks")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dedupe_covered_blocks",
        sa.Column("citation_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "sorted_ids",
            postgresql.ARRAY(sa.BIGINT()),
            server_default=sa.text("'{}'::bigint[]"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name="dedupe_covered_blocks_review_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("citation_id", name="dedupe_covered_blocks_pkey"),
    )
    with op.batch_alter_table("dedupe_covered_blocks", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dedupe_covered_blocks_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_covered_blocks_citation_id", ["citation_id"], unique=False
        )

    op.create_table(
        "dedupe_plural_block",
        sa.Column("block_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("citation_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name="dedupe_plural_block_review_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "block_id", "citation_id", name="dedupe_plural_block_pkey"
        ),
    )
    with op.batch_alter_table("dedupe_plural_block", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dedupe_plural_block_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_plural_block_citation_id", ["citation_id"], unique=False
        )

    op.create_table(
        "dedupe_blocking_map",
        sa.Column("citation_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("block_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["citation_id"],
            ["citations.id"],
            name="dedupe_blocking_map_citation_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name="dedupe_blocking_map_review_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "citation_id", "review_id", "block_key", name="dedupe_blocking_map_pkey"
        ),
    )
    with op.batch_alter_table("dedupe_blocking_map", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dedupe_blocking_map_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_blocking_map_citation_id", ["citation_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_blocking_map_block_key", ["block_key"], unique=False
        )

    op.create_table(
        "dedupe_plural_key",
        sa.Column("block_id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("block_key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name="dedupe_plural_key_review_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("block_id", name="dedupe_plural_key_pkey"),
        sa.UniqueConstraint("review_id", "block_key", name="review_id_block_key_uc"),
    )
    with op.batch_alter_table("dedupe_plural_key", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dedupe_plural_key_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_plural_key_block_key", ["block_key"], unique=False
        )

    op.create_table(
        "dedupe_smaller_coverage",
        sa.Column("citation_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("review_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("block_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column(
            "smaller_ids",
            postgresql.ARRAY(sa.BIGINT()),
            server_default=sa.text("'{}'::bigint[]"),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
            name="dedupe_smaller_coverage_review_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "citation_id", "block_id", name="dedupe_smaller_coverage_pkey"
        ),
    )
    with op.batch_alter_table("dedupe_smaller_coverage", schema=None) as batch_op:
        batch_op.create_index(
            "ix_dedupe_smaller_coverage_review_id", ["review_id"], unique=False
        )
        batch_op.create_index(
            "ix_dedupe_smaller_coverage_citation_id", ["citation_id"], unique=False
        )

    # ### end Alembic commands ###
