"""empty message

Revision ID: 1509a565a16a
Revises: e019a6c7f7ab
Create Date: 2016-09-14 22:37:03.469665

"""

# revision identifiers, used by Alembic.
revision = '1509a565a16a'
down_revision = 'e019a6c7f7ab'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citation_screenings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('exclude_reasons', postgresql.ARRAY(sa.Unicode(length=25)), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', 'citation_id', name='review_user_citation_uc')
    )
    op.create_index(op.f('ix_citation_screenings_citation_id'), 'citation_screenings', ['citation_id'], unique=False)
    op.create_index(op.f('ix_citation_screenings_review_id'), 'citation_screenings', ['review_id'], unique=False)
    op.create_index(op.f('ix_citation_screenings_status'), 'citation_screenings', ['status'], unique=False)
    op.create_index(op.f('ix_citation_screenings_user_id'), 'citation_screenings', ['user_id'], unique=False)
    op.create_table('fulltext_screenings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fulltext_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('exclude_reasons', postgresql.ARRAY(sa.Unicode(length=25)), nullable=True),
    sa.ForeignKeyConstraint(['fulltext_id'], ['fulltexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('review_id', 'user_id', 'fulltext_id', name='review_user_fulltext_uc')
    )
    op.create_index(op.f('ix_fulltext_screenings_fulltext_id'), 'fulltext_screenings', ['fulltext_id'], unique=False)
    op.create_index(op.f('ix_fulltext_screenings_review_id'), 'fulltext_screenings', ['review_id'], unique=False)
    op.create_index(op.f('ix_fulltext_screenings_status'), 'fulltext_screenings', ['status'], unique=False)
    op.create_index(op.f('ix_fulltext_screenings_user_id'), 'fulltext_screenings', ['user_id'], unique=False)
    op.drop_table('screenings')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenings',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('UTC'::text, now())"), autoincrement=False, nullable=True),
    sa.Column('review_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('citation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fulltext_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('exclude_reasons', postgresql.ARRAY(sa.VARCHAR(length=25)), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], name='screenings_citation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fulltext_id'], ['fulltexts.id'], name='screenings_fulltext_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], name='screenings_review_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='screenings_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='screenings_pkey')
    )
    op.drop_index(op.f('ix_fulltext_screenings_user_id'), table_name='fulltext_screenings')
    op.drop_index(op.f('ix_fulltext_screenings_status'), table_name='fulltext_screenings')
    op.drop_index(op.f('ix_fulltext_screenings_review_id'), table_name='fulltext_screenings')
    op.drop_index(op.f('ix_fulltext_screenings_fulltext_id'), table_name='fulltext_screenings')
    op.drop_table('fulltext_screenings')
    op.drop_index(op.f('ix_citation_screenings_user_id'), table_name='citation_screenings')
    op.drop_index(op.f('ix_citation_screenings_status'), table_name='citation_screenings')
    op.drop_index(op.f('ix_citation_screenings_review_id'), table_name='citation_screenings')
    op.drop_index(op.f('ix_citation_screenings_citation_id'), table_name='citation_screenings')
    op.drop_table('citation_screenings')
    ### end Alembic commands ###
