"""empty message

Revision ID: 1994a0e9e613
Revises: d4b5d97383f2
Create Date: 2016-10-11 22:12:41.223654

"""

# revision identifiers, used by Alembic.
revision = '1994a0e9e613'
down_revision = 'd4b5d97383f2'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulltexts', sa.Column('extracted_data', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('fulltexts', sa.Column('text_content', sa.UnicodeText(), nullable=True))
    op.drop_column('fulltexts', 'content')
    op.drop_column('fulltexts', 'extracted_info')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulltexts', sa.Column('extracted_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('fulltexts', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('fulltexts', 'text_content')
    op.drop_column('fulltexts', 'extracted_data')
    ### end Alembic commands ###
