"""Extend users password varchar

Revision ID: 1c023402f9d8
Revises: d225d270af3f
Create Date: 2023-07-06 23:43:48.522007

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1c023402f9d8"
down_revision = "d225d270af3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=60),
            type_=sa.Unicode(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.Unicode(length=256),
            type_=sa.VARCHAR(length=60),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
