"""Extend users password varchar

Revision ID: 1c023402f9d8
Revises: d225d270af3f
Create Date: 2023-07-06 23:43:48.522007

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "1c023402f9d8"
down_revision = "d225d270af3f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.VARCHAR(length=60),
            type_=sa.Unicode(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # HACK: truncate any values that don't fit in the narrower column
    # get metadata and table
    conn = op.get_bind()
    meta = sa.MetaData()
    meta.reflect(bind=conn)
    users_tbl = meta.tables["users"]
    # identify and log rows that need truncating
    stmt = sa.select(users_tbl).where(sa.func.length(users_tbl.c.password) > 60)
    for row in conn.execute(stmt):
        print(f"truncating 'password' value for row with id={row.id}")
    # truncate column data
    # NOTE: this will break the passwords, in which case presumably all users
    # would have to reset them; good thing this should only happen in a dev context!
    truncate_stmt = (
        users_tbl.update()
        .where(sa.func.length(users_tbl.c.password) > 60)
        .values(password=sa.func.substring(users_tbl.c.password, 1, 60))
    )
    conn.execute(truncate_stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "password",
            existing_type=sa.Unicode(length=256),
            type_=sa.VARCHAR(length=60),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
