"""empty message

Revision ID: 2c765db19d6e
Revises: edca8f07e6fb
Create Date: 2016-09-13 20:27:10.040369

"""

# revision identifiers, used by Alembic.
revision = '2c765db19d6e'
down_revision = 'edca8f07e6fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('fulltexts', sa.Column('review_id', sa.Integer(), nullable=False))
    op.alter_column('fulltexts', 'citation_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.create_index(op.f('ix_fulltexts_review_id'), 'fulltexts', ['review_id'], unique=False)
    op.create_foreign_key(None, 'fulltexts', 'reviews', ['review_id'], ['id'], ondelete='CASCADE')
    op.alter_column('review_plans', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'owner_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('review_plans', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'fulltexts', type_='foreignkey')
    op.drop_index(op.f('ix_fulltexts_review_id'), table_name='fulltexts')
    op.alter_column('fulltexts', 'citation_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_column('fulltexts', 'review_id')
    op.alter_column('citations', 'review_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
