"""empty message

Revision ID: 2d476c030c28
Revises: 03f0535753d7
Create Date: 2016-10-29 15:24:02.318904

"""

# revision identifiers, used by Alembic.
revision = '2d476c030c28'
down_revision = '03f0535753d7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'title', type_=sa.Unicode(length=300))
    op.alter_column('citations', 'secondary_title', type_=sa.Unicode(length=300))
    op.add_column('citation_screenings', sa.Column('citation_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_citation_screenings_citation_id'), 'citation_screenings', ['citation_id'], unique=False)
    op.create_unique_constraint('review_user_citation_uc', 'citation_screenings', ['review_id', 'user_id', 'citation_id'])
    op.drop_constraint('citation_review_user_study_uc', 'citation_screenings', type_='unique')
    op.drop_index('ix_citation_screenings_study_id', table_name='citation_screenings')
    op.drop_constraint('citation_screenings_study_id_fkey', 'citation_screenings', type_='foreignkey')
    op.create_foreign_key(None, 'citation_screenings', 'citations', ['citation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('citation_screenings', 'study_id')
    op.add_column('citations', sa.Column('status', sa.Unicode(length=20), server_default='not_screened', nullable=False))
    op.create_index(op.f('ix_citations_status'), 'citations', ['status'], unique=False)
    op.add_column('data_extractions', sa.Column('status', sa.Unicode(length=20), server_default='not_started', nullable=False))
    op.create_index(op.f('ix_data_extractions_status'), 'data_extractions', ['status'], unique=False)
    op.add_column('dedupes', sa.Column('status', sa.Unicode(length=20), nullable=False))
    op.alter_column('dedupes', 'duplicate_of',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('dedupes', 'duplicate_score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_dedupes_status'), 'dedupes', ['status'], unique=False)
    op.add_column('fulltext_screenings', sa.Column('fulltext_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_fulltext_screenings_fulltext_id'), 'fulltext_screenings', ['fulltext_id'], unique=False)
    op.create_unique_constraint('review_user_fulltext_uc', 'fulltext_screenings', ['review_id', 'user_id', 'fulltext_id'])
    op.drop_constraint('fulltext_review_user_study_uc', 'fulltext_screenings', type_='unique')
    op.drop_index('ix_fulltext_screenings_study_id', table_name='fulltext_screenings')
    op.drop_constraint('fulltext_screenings_study_id_fkey', 'fulltext_screenings', type_='foreignkey')
    op.create_foreign_key(None, 'fulltext_screenings', 'fulltexts', ['fulltext_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fulltext_screenings', 'study_id')
    op.add_column('fulltexts', sa.Column('status', sa.Unicode(length=20), server_default='not_screened', nullable=False))
    op.create_index(op.f('ix_fulltexts_status'), 'fulltexts', ['status'], unique=False)
    op.drop_index('ix_studies_citation_status', table_name='studies')
    op.drop_index('ix_studies_data_extraction_status', table_name='studies')
    op.drop_index('ix_studies_dedupe_status', table_name='studies')
    op.drop_index('ix_studies_fulltext_status', table_name='studies')
    op.drop_column('studies', 'fulltext_status')
    op.drop_column('studies', 'data_extraction_status')
    op.drop_column('studies', 'dedupe_status')
    op.drop_column('studies', 'citation_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('citations', 'title', type_=sa.Unicode(length=250))
    op.alter_column('citations', 'secondary_title', type_=sa.Unicode(length=250))
    op.add_column('studies', sa.Column('citation_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('studies', sa.Column('dedupe_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('studies', sa.Column('data_extraction_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('studies', sa.Column('fulltext_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_studies_fulltext_status', 'studies', ['fulltext_status'], unique=False)
    op.create_index('ix_studies_dedupe_status', 'studies', ['dedupe_status'], unique=False)
    op.create_index('ix_studies_data_extraction_status', 'studies', ['data_extraction_status'], unique=False)
    op.create_index('ix_studies_citation_status', 'studies', ['citation_status'], unique=False)
    op.drop_index(op.f('ix_fulltexts_status'), table_name='fulltexts')
    op.drop_column('fulltexts', 'status')
    op.add_column('fulltext_screenings', sa.Column('study_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'fulltext_screenings', type_='foreignkey')
    op.create_foreign_key('fulltext_screenings_study_id_fkey', 'fulltext_screenings', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_fulltext_screenings_study_id', 'fulltext_screenings', ['study_id'], unique=False)
    op.create_unique_constraint('fulltext_review_user_study_uc', 'fulltext_screenings', ['review_id', 'user_id', 'study_id'])
    op.drop_constraint('review_user_fulltext_uc', 'fulltext_screenings', type_='unique')
    op.drop_index(op.f('ix_fulltext_screenings_fulltext_id'), table_name='fulltext_screenings')
    op.drop_column('fulltext_screenings', 'fulltext_id')
    op.drop_index(op.f('ix_dedupes_status'), table_name='dedupes')
    op.alter_column('dedupes', 'duplicate_score',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('dedupes', 'duplicate_of',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_column('dedupes', 'status')
    op.drop_index(op.f('ix_data_extractions_status'), table_name='data_extractions')
    op.drop_column('data_extractions', 'status')
    op.drop_index(op.f('ix_citations_status'), table_name='citations')
    op.drop_column('citations', 'status')
    op.add_column('citation_screenings', sa.Column('study_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'citation_screenings', type_='foreignkey')
    op.create_foreign_key('citation_screenings_study_id_fkey', 'citation_screenings', 'studies', ['study_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_citation_screenings_study_id', 'citation_screenings', ['study_id'], unique=False)
    op.create_unique_constraint('citation_review_user_study_uc', 'citation_screenings', ['review_id', 'user_id', 'study_id'])
    op.drop_constraint('review_user_citation_uc', 'citation_screenings', type_='unique')
    op.drop_index(op.f('ix_citation_screenings_citation_id'), table_name='citation_screenings')
    op.drop_column('citation_screenings', 'citation_id')
    ### end Alembic commands ###
