"""empty message

Revision ID: 31393355beb7
Revises: 1509a565a16a
Create Date: 2016-09-14 23:19:45.381685

"""

# revision identifiers, used by Alembic.
revision = '31393355beb7'
down_revision = '1509a565a16a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('citations', 'exclude_reasons')
    op.drop_column('fulltexts', 'exclude_reasons')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulltexts', sa.Column('exclude_reasons', postgresql.ARRAY(sa.VARCHAR(length=25)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('exclude_reasons', postgresql.ARRAY(sa.VARCHAR(length=25)), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=True))
    ### end Alembic commands ###
