"""empty message

Revision ID: d4b5d97383f2
Revises: d519392ad2b1
Create Date: 2016-10-08 13:12:12.479079

"""

# revision identifiers, used by Alembic.
revision = 'd4b5d97383f2'
down_revision = 'd519392ad2b1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_plans', sa.Column('suggested_keyterms', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), server_default='{}', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_plans', 'suggested_keyterms')
    ### end Alembic commands ###
