"""empty message

Revision ID: d519392ad2b1
Revises: 2ebb88a7872d
Create Date: 2016-10-04 01:44:35.292476

"""

# revision identifiers, used by Alembic.
revision = 'd519392ad2b1'
down_revision = '2ebb88a7872d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dedupe_covered_blocks',
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('sorted_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id')
    )
    op.create_index(op.f('ix_dedupe_covered_blocks_citation_id'), 'dedupe_covered_blocks', ['citation_id'], unique=False)
    op.create_index(op.f('ix_dedupe_covered_blocks_review_id'), 'dedupe_covered_blocks', ['review_id'], unique=False)
    op.create_table('dedupe_plural_block',
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id', 'citation_id')
    )
    op.create_index(op.f('ix_dedupe_plural_block_citation_id'), 'dedupe_plural_block', ['citation_id'], unique=False)
    op.create_index(op.f('ix_dedupe_plural_block_review_id'), 'dedupe_plural_block', ['review_id'], unique=False)
    op.create_table('dedupe_plural_key',
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('block_key', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('review_id', 'block_key', name='review_id_block_key_uc')
    )
    op.create_index(op.f('ix_dedupe_plural_key_block_key'), 'dedupe_plural_key', ['block_key'], unique=False)
    op.create_index(op.f('ix_dedupe_plural_key_review_id'), 'dedupe_plural_key', ['review_id'], unique=False)
    op.create_table('dedupe_smaller_coverage',
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.BigInteger(), nullable=False),
    sa.Column('smaller_ids', postgresql.ARRAY(sa.BigInteger()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id', 'block_id')
    )
    op.create_index(op.f('ix_dedupe_smaller_coverage_citation_id'), 'dedupe_smaller_coverage', ['citation_id'], unique=False)
    op.create_index(op.f('ix_dedupe_smaller_coverage_review_id'), 'dedupe_smaller_coverage', ['review_id'], unique=False)
    op.create_table('dedupe_blocking_map',
    sa.Column('citation_id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('block_key', sa.UnicodeText(), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('citation_id', 'review_id', 'block_key')
    )
    op.create_index(op.f('ix_dedupe_blocking_map_block_key'), 'dedupe_blocking_map', ['block_key'], unique=False)
    op.create_index(op.f('ix_dedupe_blocking_map_citation_id'), 'dedupe_blocking_map', ['citation_id'], unique=False)
    op.create_index(op.f('ix_dedupe_blocking_map_review_id'), 'dedupe_blocking_map', ['review_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dedupe_blocking_map_review_id'), table_name='dedupe_blocking_map')
    op.drop_index(op.f('ix_dedupe_blocking_map_citation_id'), table_name='dedupe_blocking_map')
    op.drop_index(op.f('ix_dedupe_blocking_map_block_key'), table_name='dedupe_blocking_map')
    op.drop_table('dedupe_blocking_map')
    op.drop_index(op.f('ix_dedupe_smaller_coverage_review_id'), table_name='dedupe_smaller_coverage')
    op.drop_index(op.f('ix_dedupe_smaller_coverage_citation_id'), table_name='dedupe_smaller_coverage')
    op.drop_table('dedupe_smaller_coverage')
    op.drop_index(op.f('ix_dedupe_plural_key_review_id'), table_name='dedupe_plural_key')
    op.drop_index(op.f('ix_dedupe_plural_key_block_key'), table_name='dedupe_plural_key')
    op.drop_table('dedupe_plural_key')
    op.drop_index(op.f('ix_dedupe_plural_block_review_id'), table_name='dedupe_plural_block')
    op.drop_index(op.f('ix_dedupe_plural_block_citation_id'), table_name='dedupe_plural_block')
    op.drop_table('dedupe_plural_block')
    op.drop_index(op.f('ix_dedupe_covered_blocks_review_id'), table_name='dedupe_covered_blocks')
    op.drop_index(op.f('ix_dedupe_covered_blocks_citation_id'), table_name='dedupe_covered_blocks')
    op.drop_table('dedupe_covered_blocks')
    ### end Alembic commands ###
