"""empty message

Revision ID: de440d9ae8bf
Revises: 8189c2d935cc
Create Date: 2017-01-16 10:28:15.334734

"""

# revision identifiers, used by Alembic.
revision = 'de440d9ae8bf'
down_revision = '8189c2d935cc'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'dedupe_status', server_default='not_screened', nullable=False)
    op.add_column('reviews', sa.Column('num_citations_excluded', sa.Integer(), server_default='0', nullable=False))
    op.add_column('reviews', sa.Column('num_citations_included', sa.Integer(), server_default='0', nullable=False))
    op.add_column('reviews', sa.Column('num_fulltexts_excluded', sa.Integer(), server_default='0', nullable=False))
    op.add_column('reviews', sa.Column('num_fulltexts_included', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('studies', 'dedupe_status', server_default=None, nullable=True)
    op.drop_column('reviews', 'num_fulltexts_included')
    op.drop_column('reviews', 'num_fulltexts_excluded')
    op.drop_column('reviews', 'num_citations_included')
    op.drop_column('reviews', 'num_citations_excluded')
    # ### end Alembic commands ###
