"""empty message

Revision ID: e019a6c7f7ab
Revises: 2c765db19d6e
Create Date: 2016-09-14 20:59:32.692548

"""

# revision identifiers, used by Alembic.
revision = 'e019a6c7f7ab'
down_revision = '2c765db19d6e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screenings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=True),
    sa.Column('fulltext_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Unicode(length=20), nullable=False),
    sa.Column('exclude_reasons', postgresql.ARRAY(sa.Unicode(length=25)), nullable=False),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fulltext_id'], ['fulltexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screenings_citation_id'), 'screenings', ['citation_id'], unique=False)
    op.create_index(op.f('ix_screenings_fulltext_id'), 'screenings', ['fulltext_id'], unique=False)
    op.create_index(op.f('ix_screenings_review_id'), 'screenings', ['review_id'], unique=False)
    op.create_index(op.f('ix_screenings_status'), 'screenings', ['status'], unique=False)
    op.create_index(op.f('ix_screenings_user_id'), 'screenings', ['user_id'], unique=False)
    op.drop_column('citations', 'screening')
    op.drop_column('fulltexts', 'screening')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fulltexts', sa.Column('screening', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('citations', sa.Column('screening', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_screenings_user_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_status'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_review_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_fulltext_id'), table_name='screenings')
    op.drop_index(op.f('ix_screenings_citation_id'), table_name='screenings')
    op.drop_table('screenings')
    ### end Alembic commands ###
