"""empty message

Revision ID: 0bef5766f2ec
Revises: None
Create Date: 2016-08-31 22:44:53.509022

"""

# revision identifiers, used by Alembic.
revision = '0bef5766f2ec'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP(0) AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('name', sa.Unicode(length=200), nullable=False),
    sa.Column('email', sa.Unicode(length=200), nullable=False),
    sa.Column('password', sa.Unicode(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP(0) AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('name', sa.Unicode(length=500), nullable=False),
    sa.Column('description', sa.UnicodeText(), nullable=True),
    sa.Column('settings', postgresql.JSONB(none_as_null=True), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_owner_user_id'), 'reviews', ['owner_user_id'], unique=False)
    op.create_table('citations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP(0) AT TIME ZONE 'UTC')"), nullable=True),
    sa.Column('type_of_work', sa.Unicode(length=25), nullable=True),
    sa.Column('title', sa.Unicode(length=250), nullable=True),
    sa.Column('secondary_title', sa.Unicode(length=250), nullable=True),
    sa.Column('pub_year', sa.SmallInteger(), nullable=True),
    sa.Column('pub_month', sa.SmallInteger(), nullable=True),
    sa.Column('authors', postgresql.ARRAY(sa.Unicode(length=100)), nullable=True),
    sa.Column('abstract', sa.UnicodeText(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Unicode(length=100)), nullable=True),
    sa.Column('type_of_reference', sa.Unicode(length=50), nullable=True),
    sa.Column('journal_name', sa.Unicode(length=100), nullable=True),
    sa.Column('volume', sa.Unicode(length=20), nullable=True),
    sa.Column('issue_number', sa.Unicode(length=20), nullable=True),
    sa.Column('doi', sa.Unicode(length=100), nullable=True),
    sa.Column('issn', sa.Unicode(length=20), nullable=True),
    sa.Column('publisher', sa.Unicode(length=100), nullable=True),
    sa.Column('language', sa.Unicode(length=50), nullable=True),
    sa.Column('other_fields', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citations_review_id'), 'citations', ['review_id'], unique=False)
    op.create_table('review_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('objective', sa.UnicodeText(), nullable=True),
    sa.Column('research_questions', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.Column('pico', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.Column('keyterms', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.Column('selection_criteria', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_plans_review_id'), 'review_plans', ['review_id'], unique=False)
    op.create_table('users_to_reviews',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_index(op.f('ix_users_to_reviews_review_id'), 'users_to_reviews', ['review_id'], unique=False)
    op.create_index(op.f('ix_users_to_reviews_user_id'), 'users_to_reviews', ['user_id'], unique=False)
    op.create_table('citation_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('citation_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Unicode(length=15), nullable=False),
    sa.Column('exclude_reason', sa.Unicode(length=20), nullable=True),
    sa.Column('deduplication', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.Column('citation_screening', postgresql.JSONB(none_as_null=True), nullable=True),
    sa.ForeignKeyConstraint(['citation_id'], ['citations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_statuses_citation_id'), 'citation_statuses', ['citation_id'], unique=False)
    op.create_index(op.f('ix_citation_statuses_status'), 'citation_statuses', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citation_statuses_status'), table_name='citation_statuses')
    op.drop_index(op.f('ix_citation_statuses_citation_id'), table_name='citation_statuses')
    op.drop_table('citation_statuses')
    op.drop_index(op.f('ix_users_to_reviews_user_id'), table_name='users_to_reviews')
    op.drop_index(op.f('ix_users_to_reviews_review_id'), table_name='users_to_reviews')
    op.drop_table('users_to_reviews')
    op.drop_index(op.f('ix_review_plans_review_id'), table_name='review_plans')
    op.drop_table('review_plans')
    op.drop_index(op.f('ix_citations_review_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_reviews_owner_user_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    ### end Alembic commands ###
