"""empty message

Revision ID: 44f965fb2792
Revises: 00e303a6d251
Create Date: 2016-09-05 16:30:12.055408

"""

# revision identifiers, used by Alembic.
revision = '44f965fb2792'
down_revision = '00e303a6d251'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('num_citation_screening_reviewers', sa.SmallInteger(), server_default=sa.text('1'), nullable=False))
    op.add_column('reviews', sa.Column('num_fulltext_screening_reviewers', sa.SmallInteger(), server_default=sa.text('1'), nullable=False))
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(length=25),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('reviews', 'settings')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('settings', postgresql.JSONB(), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.alter_column('reviews', 'status',
               existing_type=sa.VARCHAR(length=25),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_column('reviews', 'num_fulltext_screening_reviewers')
    op.drop_column('reviews', 'num_citation_screening_reviewers')
    ### end Alembic commands ###
