"""empty message

Revision ID: 9688b26f29c2
Revises: 8ea148fc2384
Create Date: 2016-09-03 21:09:00.230068

"""

# revision identifiers, used by Alembic.
revision = '9688b26f29c2'
down_revision = '8ea148fc2384'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('deduplication', postgresql.JSONB(none_as_null=True), nullable=True))
    op.drop_column('studies', 'exclude_reason')
    op.drop_column('studies', 'duplication')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('studies', sa.Column('duplication', postgresql.JSONB(), autoincrement=False, nullable=True))
    op.add_column('studies', sa.Column('exclude_reason', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('studies', 'deduplication')
    ### end Alembic commands ###
